import "../common/styles/globals.css";
import { ThemeProvider, Header } from "@/common/components";
import { fontSfProDisplay } from "@/common/fonts/sf-display-pro";

export const metadata = {
  title: "Baku Electronics",
  description: "Generated by create next app",
  icons: "/images/logos/main-logo.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${fontSfProDisplay.variable} flex justify-center` }>
        <div className="max-w-[1350px]">
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
